website:
  reader-mode: true
  search: 
    location: navbar
    type: overlay
  page-navigation: true
  back-to-top-navigation: true

title: ScrivQ 24
author: Bernardo C D A Vasconcelos
license: CC BY-NC-SA
description: A Scrivener template project for Quarto capable of exporting multiple files, handling cross-references, and keeping a bibliography.
copyright:
  year: 2024
project:
  preview:
    port: 5556
    watch-inputs: true
    navigate: true


filters:
  - citetools


execute:
  output: asis
  cache: true
  freeze: auto


format:


  html:

    template: _extensions/templates/html/template.html # template.html

    template-partials:
      - _extensions/templates/html/html.template # html.template
      - _extensions/templates/html/title-block.html # title-block.html
      - _extensions/templates/html/template.html # template.html
      - _extensions/templates/html/styles.html # styles.html
      - _extensions/templates/html/html.styles # html.styles
      - _extensions/templates/html/toc.html # toc.html
      - _extensions/templates/html/metadata.html # metadata.html

    theme: # https://bootswatch.com default cerulean cosmo cyborg darkly flatly journal litera lumen lux materia minty morph pulse quartz sandstone simplex sketchy slate solar spacelab superhero united vapor yeti zephyr
      light: [Pulse] 
      dark: [Darkly]

    embed-resources: true
    self-contained-math: true
    anchor-sections: true
    smooth-scroll: true
    code-links:
      - text: Compile Script
        icon: file-code
        href: compile.rb


# Toc
    toc: true
    toc-depth: 3
    toc-expand: 2
    toc-location: left
    toc-title: Contents
    number-sections: true
    number-depth: 3

# Code
    code-link: true
    code-copy: true
    code-tools: true
    code-fold: show
    highlight-style: github
    code-line-numbers: true
    code-overflow: wrap

# Fonts
    linestretch: 1.5
    fontsize: 12pt
    fontfamily: Alegreya
    mainfont: Alegreya
    sansfont: Alegreya Sans
    monofont: Source Code Pro

# Layout
    cap-location: bottom
    fig-cap-location: bottom
    tbl-cap-location: bottom
    reference-location: margin
    appendix-style: default
    link-fields: true

    include-before: |
      <style>
      @import url('https://fonts.googleapis.com/css2?family=Alegreya+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Alegreya:ital,wght@0,400;0,700;1,400;1,700&display=swap');
      @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&family=Source+Serif+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap');
      </style>


  pdf:
    link-fields: true
    pdf-engine: lualatex
    documentclass: scrbook
    classoption:
      - oneside
      - cleardoublepage=empty
      - numbers=noenddot
      - titlepage
      - toclink=all
      - toc=bibliography
      - headinclude
      - footinclude
    indent: true
    cap-location: bottom
    fig-cap-location: bottom
    tbl-cap-location: bottom
    pagestyle: headings
    hyperrefoptions:
      - pdfstartview=FitR
      - pdfpagemode=UseOutlines
      - breaklinks=true
      - pageanchor=true
      - linktoc=all
      - hyperfootnotes=false
      - bookmarksnumbered
    header-includes: |
      \usepackage{setspace}
      \usepackage{etoolbox}
      \usepackage{metalogo}
      \newfontfamily{\sanskritfont}{Noto Serif Devanagari} 
      \newcommand{\skt}[1]{\foreignlanguage{sanskrit}{\selectfont\sanskritfont #1}}
      \newenvironment{sanskrit}{\begingroup
      \selectlanguage{sanskrit}\selectfont\sanskritfont\normalsize}{\endgroup}
      \usepackage{xcolor}
      \definecolor{CTlink}{named}{RoyalBlue} % RoyalBlue {cmyk}{1, 0.50, 0, 0}
      \definecolor{halfgray}{gray}{0.55} % chapt numbers semi transp .5 .55 .6 .0
      \setsansfont{AlegreyaSans-Regular}[Extension = .otf , BoldFont = AlegreyaSans-Bold , ItalicFont = AlegreyaSans-Italic , BoldItalicFont = AlegreyaSans-BoldItalic ]
    standalone: true
    latex-auto-install: true
    latex-auto-mk: true
    latex-tinytex: true
    keep-tex: true
    babel-lang: english
    babel-otherlangs:
      - brazilian
      - ancientgreek
      - sanskrit
    toc: true
    toc-depth: 3
    toc-title: Summary
    lof: true
    lot: true
    number-sections: true
    number-depth: 3
    top-level-division: chapter
    linestretch: 1.3
    fontsize: 10pt
    fontfamily: Alegreya
    mainfont: Gentium Plus
    mainfontoptions:
      - Numbers=Proportional
      - Numbers=Lowercase
    sansfont: Alegreya Sans
    monofont: Ubuntu Mono
    colorlinks: true
    citecolor: RoyalBlue
    filecolor: RoyalBlue
    linkcolor: RoyalBlue
    toccolor: RoyalBlue
    urlcolor: RoyalBlue
    highlight-style: github
    code-line-numbers: true
    code-overflow: wrap
    ascii: false
    appendix-style: default
    float: true
    csquotes: true
    biblio-title: Bibliography


  typst-citations:
    link-fields: false # if true, compilation fails
    title: Hello, ScrivQ
    author: Bernardo Vasconcelos
    date: 2024-11
    abstract: The Abstract
    toc: false
    number-sections: true
    number-depth: 3
    fontsize: 12pt
    mainfont: Gentium Plus
    sansfont: Alegreya Sans
    monofont: Source Code Pro
    tbl-cap-location: bottom
    keep-typ: true
    prefer-html: true
    papersize: a4 
    template: _extensions/templates/typst/orange/template.typ # template
    template-partials:
        - _extensions/templates/typst/definitions.typ # definitions
        - _extensions/templates/typst/orange/typst-template.typ # typst-template
        - _extensions/templates/typst/typst-show.typ # typst-show
        - _extensions/templates/typst/notes.typ # notes
        - _extensions/templates/typst/biblio.typ # biblio


  docx:
    subject: Hello, ScrivQ
    keywords: [ScrivQ, Scrivener, Quarto, Pandoc]
    toc: true
    toc-depth: 3
    toc-title: Summary
    number-sections: true
    number-depth: 3
    sidebar-width: 300px
    body-width: 900px
    margin-width: 300px
    gutter-width: 1.5rem
    embed-resources: false
    self-contained-math: false
    standalone: true
    highlight-style: github


validate-yaml: false
prefer-html: true
citation: true
cite-method: citeproc
citeproc: false # CiteTools will call Citeproc

csl: _extensions/csl/abnt-phi.csl # ABNT-Phi.csl
verbose: false
verbosity: ERROR
notes-after-punctuation: true

link-citations: true
link-bibliography: true

bibliography_primary-sources: "refs/primary-sources.yml" # primary sources
bibliography_secondary-sources: "refs/secondary-sources.yml" # secondary sources
bibliography_workflow: "refs/workflow.bib" # Workflow
bibliography_songs: "refs/songs.yml" # Songs
bibliography_paintings: "refs/paintings.yml" # Paintings

